//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class cooler_
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Specs { get; set; }
        public string Image { get; set; }
        public string Manufacture { get; set; }
        public string Category { get; set; }
    }
}
