//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_managment_labEntities : DbContext
    {
        public db_managment_labEntities()
            : base("name=db_managment_labEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cooler_> cooler_ { get; set; }
        public virtual DbSet<gpu_> gpu_ { get; set; }
        public virtual DbSet<hard_disk_> hard_disk_ { get; set; }
        public virtual DbSet<motherboard_> motherboard_ { get; set; }
        public virtual DbSet<optical_> optical_ { get; set; }
        public virtual DbSet<pc_case_> pc_case_ { get; set; }
        public virtual DbSet<processor_> processor_ { get; set; }
        public virtual DbSet<ram_> ram_ { get; set; }
        public virtual DbSet<trofo_> trofo_ { get; set; }
    }
}
