//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.Web.Mvc;

	public partial class announcement
	{
		public System.Guid GID { get; set; }
		[Required(ErrorMessage = "Title field is required!")]
		public string Title { get; set; }
		[AllowHtml]
		[Required(ErrorMessage = "Body field is required!")]
		public string body_text { get; set; }
		public string username { get; set; }
		public System.DateTime date { get; set; }
	}
}

