//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class gpu
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public gpu()
		{
			this.Pclabs = new HashSet<Pclab>();
		}

		public System.Guid GID { get; set; }
		[Required(ErrorMessage = "Name field is required!")]
		[StringLength(150, MinimumLength = 4, ErrorMessage = "Name must be greater than {2} characters and less than {1} characters.")]
		public string Name { get; set; }
		[Required(ErrorMessage = "Specs field is required!")]
		[StringLength(150, MinimumLength = 4, ErrorMessage = "Name must be greater than {2} characters and less than {1} characters.")]
		public string Specs { get; set; }
		[Required(ErrorMessage = "Image field is required!")]
		public string Image { get; set; }
		[Required(ErrorMessage = "Manufacture field is required!")]
		public string Manufacture { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Pclab> Pclabs { get; set; }
	}
}
