//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_managment_labEntities4 : DbContext
    {
        public db_managment_labEntities4()
            : base("name=db_managment_labEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryCooler> CategoryCoolers { get; set; }
        public virtual DbSet<CategoryHardDisk> CategoryHardDisks { get; set; }
        public virtual DbSet<cooler> coolers { get; set; }
        public virtual DbSet<gpu> gpus { get; set; }
        public virtual DbSet<hard_disk> hard_disk { get; set; }
        public virtual DbSet<motherboard> motherboards { get; set; }
        public virtual DbSet<optical> opticals { get; set; }
        public virtual DbSet<pc_case> pc_case { get; set; }
        public virtual DbSet<processor> processors { get; set; }
        public virtual DbSet<psu> psus { get; set; }
        public virtual DbSet<ram> rams { get; set; }
        public virtual DbSet<Pclab> Pclabs { get; set; }
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<CategoryProblem> CategoryProblems { get; set; }
        public virtual DbSet<PcProblem> PcProblems { get; set; }
        public virtual DbSet<lab> labs { get; set; }
    }
}
