//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.Web.Mvc;

	public partial class Pclab
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Pclab()
		{
			this.PcProblems = new HashSet<PcProblem>();
		}
		public System.Guid GID { get; set; }
		[Required(ErrorMessage = "Name field is required!")]
		public string NamePc { get; set; }
		public string temp { get; set; }
		public Nullable<System.Guid> coolerID { get; set; }
		public string cool { get; set; }
		[Required(ErrorMessage = "Motherboard is required.Select on from the list!")]
		public Nullable<System.Guid> motherboardID { get; set; }
		public string mother { get; set; }
		[Required(ErrorMessage = "Ram is required.Select on from the list!")]
		public Nullable<System.Guid> ramID { get; set; }
		public string rm { get; set; }
		[Required(ErrorMessage = "Hard Disk is required.Select on from the list!")]
		public Nullable<System.Guid> hard_diskID { get; set; }
		public string hdd { get; set; }
		[Required(ErrorMessage = "Graphical card is required.Select on from the list!")]
		public Nullable<System.Guid> gpuID { get; set; }
		public string gp { get; set; }
		public Nullable<System.Guid> opticalID { get; set; }
		public string opt { get; set; }
		[Required(ErrorMessage = "Case is required.Select on from the list!")]
		public Nullable<System.Guid> caseID { get; set; }

		public string cs { get; set; }
		[Required(ErrorMessage = "Processor is required.Select on from the list!")]
		public Nullable<System.Guid> cpuID { get; set; }
		public string cp { get; set; }
		[Required(ErrorMessage = "Psu is required.Select on from the list!")]
		public Nullable<System.Guid> psuID { get; set; }
		[Required(ErrorMessage = "Choose one of the laboratory rooms!")]
		public Nullable<int> lab_id { get; set; }
		public string ps { get; set; }

		public virtual cooler cooler { get; set; }
		public virtual motherboard motherboard { get; set; }
		public virtual ram ram { get; set; }
		public virtual hard_disk hard_disk { get; set; }
		public virtual gpu gpu { get; set; }
		public virtual optical optical { get; set; }
		public virtual pc_case pc_case { get; set; }
		public virtual processor processor { get; set; }
		public virtual psu psu { get; set; }
		public virtual lab lab { get; set; }
		public List<cooler> coolers { get; set; }
		public List<gpu> gpus { get; set; }
		public List<hard_disk> hard_disks { get; set; }
		public List<motherboard> motherboards { get; set; }
		public List<optical> opticals { get; set; }
		public List<pc_case> pc_cases { get; set; }
		public List<processor> processors { get; set; }
		public List<psu> psus { get; set; }
		public List<ram> rams { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<PcProblem> PcProblems { get; set; }
	}
}